// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7CeIsK2NrWbs8HxsQkU3e29GHP8twtYw',
    appId: '1:850911623880:android:11f068cde9b47e07ce43fd',
    messagingSenderId: '850911623880',
    projectId: 'eventify-8213b',
    storageBucket: 'eventify-8213b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJWzJJA_69hOHnZwjvUf9beV-jeTyoD4',
    appId: '1:850911623880:ios:d99ed26c8d8f365dce43fd',
    messagingSenderId: '850911623880',
    projectId: 'eventify-8213b',
    storageBucket: 'eventify-8213b.appspot.com',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzJWzJJA_69hOHnZwjvUf9beV-jeTyoD4',
    appId: '1:850911623880:ios:d99ed26c8d8f365dce43fd',
    messagingSenderId: '850911623880',
    projectId: 'eventify-8213b',
    storageBucket: 'eventify-8213b.appspot.com',
    iosBundleId: 'com.example.eventify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFn-wRCi8h17x16nz7bRotetueFDDynq8',
    appId: '1:850911623880:web:a04205634d529234ce43fd',
    messagingSenderId: '850911623880',
    projectId: 'eventify-8213b',
    authDomain: 'eventify-8213b.firebaseapp.com',
    storageBucket: 'eventify-8213b.appspot.com',
    measurementId: 'G-81GMNGNE1E',
  );

}